#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on disco-stein."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='disco')
    deployment.run_tests()
