#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on bionic-stein."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='bionic',
                                        openstack='cloud:bionic-stein',
                                        source='cloud:bionic-stein')
    deployment.run_tests()
