#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on bionic-train."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='bionic',
                                        openstack='cloud:bionic-train',
                                        source='cloud:bionic-train')
    deployment.run_tests()
